apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-statsd-exporter.fullname" . }}
  labels:
    {{- include "prometheus-statsd-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
  - path: /metrics
    port: web
  selector:
    matchLabels:
      app: {{ include "prometheus-statsd-exporter.fullname" . }}
