apiVersion: v1
entries:
  cert-manager-crds:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-05-14T03:57:48.060427479Z"
    description: Cert Manager CRDs
    digest: 8e762f31450b7a68777db7bc7a084d406756827a05f0bc1efd9ba8c39440c001
    name: cert-manager-crds
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/cert-manager-crds-0.0.1.tgz
    version: 0.0.1
  do-pvcs:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-05-14T03:57:48.070303295Z"
    description: Digital Ocean PVCs
    digest: 5319baa02f5ac39d0b30670bd89dbaa9b68a0b1f4ed12ff0372f3dc27a651782
    name: do-pvcs
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/do-pvcs-0.0.1.tgz
    version: 0.0.1
  gce-pvcs:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-05-14T03:57:48.070514893Z"
    description: GCE PVCs
    digest: fc3edeae12dc39d74a95b49439dc6446f883e21e2826f0268f0bd04101119f18
    name: gce-pvcs
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/gce-pvcs-0.0.2.tgz
    version: 0.0.2
  letsencrypt-issuer:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-05-14T03:57:48.070765491Z"
    description: Letsencrypt
    digest: 0736f0bf3fc521606748e7ff63d24725a5a2f5b4e3dcb6512df21aa3a5de3a9d
    name: letsencrypt-issuer
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/letsencrypt-issuer-0.0.2.tgz
    version: 0.0.2
  namespaces:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-05-14T03:57:48.07094389Z"
    description: Namespaces
    digest: 0909cf3705bfd1c741812f8e5d586ca7a5ce3788b0093e1d6d646a13a6e3f7aa
    name: namespaces
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/namespaces-0.0.1.tgz
    version: 0.0.1
  prometheus-statsd-exporter:
  - apiVersion: v2
    appVersion: v0.15.0
    created: "2020-05-14T03:57:48.071397086Z"
    description: A Helm chart for Kubernetes
    digest: ea177603d3065d4248b62d50485f4a8a124d1b0f0e458572062269c08c9b35a2
    name: prometheus-statsd-exporter
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/prometheus-statsd-exporter-0.1.31.tgz
    version: 0.1.31
  services:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-05-14T03:57:48.071648184Z"
    description: Services
    digest: 843b27c9134beaf83c841d6bd8dabc67188db6f49b2b749af6c2c8c4cf9e886e
    name: services
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/services-0.0.1.tgz
    version: 0.0.1
generated: "2020-05-14T03:57:48.029963237Z"
