apiVersion: v1
entries:
  cert-manager-crds:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-07-09T20:52:25.796970165Z"
    description: Cert Manager CRDs
    digest: 16b2c4f31461007cd6a8f5ba24edf9e3ebf190954356b2456276b9262c81e038
    name: cert-manager-crds
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/cert-manager-crds-0.0.1.tgz
    version: 0.0.1
  do-pvcs:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-07-09T20:52:25.797224865Z"
    description: Digital Ocean PVCs
    digest: 5d0eedf7aae5746edd89c04b399c8d6c561726759350abfb42e43e4e5b06747e
    name: do-pvcs
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/do-pvcs-0.0.2.tgz
    version: 0.0.2
  gce-pvcs:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-07-09T20:52:25.797434966Z"
    description: GCE PVCs
    digest: 281e8abe1704a59ee38c12bdad39b190576ffee60aea2889f3792e5d31490814
    name: gce-pvcs
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/gce-pvcs-0.0.2.tgz
    version: 0.0.2
  generic-application:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-07-09T20:52:25.799196868Z"
    dependencies:
    - name: oauth2-proxy
      repository: '@stable'
      version: 3.2.0
    description: A Helm chart for Kubernetes
    digest: f61071b71e4bda65b612f16c8be38682f371ab0847a097bb53e1f73b9d851f1d
    name: generic-application
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/generic-application-0.1.1.tgz
    version: 0.1.1
  letsencrypt-issuer:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-07-09T20:52:25.799423268Z"
    description: Letsencrypt
    digest: a60b5f51ef09ee703d9d879623cf2e54cb06c9247080fc1a134ec839379f1551
    name: letsencrypt-issuer
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/letsencrypt-issuer-0.0.2.tgz
    version: 0.0.2
  namespaces:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-07-09T20:52:25.799609768Z"
    description: Namespaces
    digest: aa061d3ecb53b2a8f1315985414bfe55303edf2bc81eb9d68db1322e4d834ab4
    name: namespaces
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/namespaces-0.0.1.tgz
    version: 0.0.1
  prometheus-statsd-exporter:
  - apiVersion: v2
    appVersion: v0.15.0
    created: "2020-07-09T20:52:25.800105269Z"
    description: A Helm chart for Kubernetes
    digest: d2e170b85b5a65b02978152d8adec1fa6371aa220082280a434f5057e4db4da2
    name: prometheus-statsd-exporter
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/prometheus-statsd-exporter-0.1.31.tgz
    version: 0.1.31
  services:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-07-09T20:52:25.800368769Z"
    description: Services
    digest: e5cf576ae06e5021b70afa2dc6320d8e454e4ca5b22012aa686a09cebe0f3a17
    name: services
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/services-0.0.1.tgz
    version: 0.0.1
generated: "2020-07-09T20:52:25.769708331Z"
