apiVersion: v1
entries:
  gce-pvcs:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-05-11T07:03:46.9380934Z"
    description: GCE PVCs
    digest: c0f23688d6920c3aa1610ed669471ff64e638fbdae16bfa1bff1ac4a4e437700
    name: gce-pvcs
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/gce-pvcs-0.0.2.tgz
    version: 0.0.2
  letsencrypt-issuer:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-05-11T07:03:46.938311502Z"
    description: Letsencrypt
    digest: 24bd0929df3088385bb962e27b4dc397d39eecac333da6d3728c1bd1c63c2e8c
    name: letsencrypt-issuer
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/letsencrypt-issuer-0.0.2.tgz
    version: 0.0.2
  namespaces:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-05-11T07:03:46.938484004Z"
    description: Namespaces
    digest: 299f94631767768819a22663146f09c4f73c7c40b1784276ffaaade93565efc7
    name: namespaces
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/namespaces-0.0.1.tgz
    version: 0.0.1
  prometheus-statsd-exporter:
  - apiVersion: v2
    appVersion: v0.15.0
    created: "2020-05-11T07:03:46.938881708Z"
    description: A Helm chart for Kubernetes
    digest: 98dbebde8f5abd03fb6beffc947efc67aab2996f6182d7b9e9d6fd5d53a3f164
    name: prometheus-statsd-exporter
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/prometheus-statsd-exporter-0.1.31.tgz
    version: 0.1.31
generated: "2020-05-11T07:03:46.937580795Z"
