apiVersion: v1
entries:
  prometheus-statsd-exporter:
  - apiVersion: v2
    appVersion: v0.15.0
    created: "2020-04-30T22:21:11.369445056Z"
    description: A Helm chart for Kubernetes
    digest: 36b2e17480a6996cd69fe7af4177360092733a63c22753246a2cff5e35ec6bf5
    name: prometheus-statsd-exporter
    type: application
    urls:
    - https://razvvan.github.io/charts/charts/prometheus-statsd-exporter-0.1.31.tgz
    version: 0.1.31
generated: "2020-04-30T22:21:11.368896656Z"
