apiVersion: v1
entries:
  cert-manager-crds:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-09-04T17:56:39.831523655Z"
    description: Cert Manager CRDs
    digest: e0899280f0d36aa4cadd174facf6f3f79f5fb8857bdbb3b66684e954c5a61b34
    name: cert-manager-crds
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/cert-manager-crds-0.0.1.tgz
    version: 0.0.1
  do-pvcs:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-09-04T17:56:39.831758455Z"
    description: Digital Ocean PVCs
    digest: ce3371ad4f84bf3feca5a0b73389f557a8a2a96e4d4356d65c599cacbadf0820
    name: do-pvcs
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/do-pvcs-0.0.2.tgz
    version: 0.0.2
  gce-pvcs:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-09-04T17:56:39.831960255Z"
    description: GCE PVCs
    digest: fe9af257b5c599cebb3977ab6560b5d20f276d06ae45fd8ff9c75f53540a9fe0
    name: gce-pvcs
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/gce-pvcs-0.0.2.tgz
    version: 0.0.2
  generic-application:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-09-04T17:56:39.832585155Z"
    description: A Helm chart for Kubernetes
    digest: 9227354a73c6a5b17015ad87b69ffbad41e3957cb857bb889b75c201ea7bbaeb
    name: generic-application
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/generic-application-0.1.13.tgz
    version: 0.1.13
  letsencrypt-issuer:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-09-04T17:56:39.832788156Z"
    description: Letsencrypt
    digest: 7bd6308e5d414486444e70ee688dc44a0e75052a043703cc566c9a8dfbaf0a40
    name: letsencrypt-issuer
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/letsencrypt-issuer-0.0.2.tgz
    version: 0.0.2
  namespaces:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-09-04T17:56:39.832955356Z"
    description: Namespaces
    digest: b654a9d7e29cd7f07ab6c782bcf466eb653711bcebf679b38e0acf41ec69ef3f
    name: namespaces
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/namespaces-0.0.1.tgz
    version: 0.0.1
  oauth2-proxy-with-ingress:
  - apiVersion: v2
    appVersion: 3.2.0
    created: "2020-09-04T17:56:39.835216457Z"
    dependencies:
    - name: oauth2-proxy
      repository: '@stable'
      version: 3.2.0
    description: A Helm chart for Kubernetes
    digest: ff1f539582e41ca48dbbb771cd440933fd77382e3bb964bd3c797b66815e0451
    name: oauth2-proxy-with-ingress
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/oauth2-proxy-with-ingress-0.0.5.tgz
    version: 0.0.5
  prometheus-statsd-exporter:
  - apiVersion: v2
    appVersion: v0.15.0
    created: "2020-09-04T17:56:39.835826558Z"
    description: A Helm chart for Kubernetes
    digest: b02170d7ed5d7d63d8084e147e0415864814792f1bd81637a247d560cc69a189
    name: prometheus-statsd-exporter
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/prometheus-statsd-exporter-0.1.31.tgz
    version: 0.1.31
  secret-spreader:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-09-04T17:56:39.836129258Z"
    description: Spreads secrets to multiple namespaces
    digest: e603f53b2934f85156983faadf8bedec8f87cb95a88b5dbdcaf37250b2ea9eed
    name: secret-spreader
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/secret-spreader-0.0.2.tgz
    version: 0.0.2
  services:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-09-04T17:56:39.836428958Z"
    description: Services
    digest: 2ea3e3c66e74a449cc19eda4acd9f915c5840ddb445544844e77d1905b60519c
    name: services
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/services-0.0.1.tgz
    version: 0.0.1
generated: "2020-09-04T17:56:39.829168053Z"
