{{- range .Values.disks }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .prefix }}-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .sizeInG }}Gi
  csi:
    driver: dobs.csi.digitalocean.com
    fsType: ext4
    volumeHandle: {{ .volumeHandle }}
  storageClassName: {{ .storageClassName }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .prefix }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .sizeInG }}Gi
  storageClassName: {{ .storageClassName }}
  volumeName: "{{ .prefix }}-pv"
{{- end }}

