{{- $fullName := include "generic-application.fullname" . -}}
{{- range .Values.ingress.hosts }}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-oauth2-proxy
spec:
  rules:
  - host: {{ .host | quote }}
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}-oauth2-proxy
          servicePort: 80
        path: /oauth2
  tls:
  - hosts:
    - {{ .host | quote }}
    secretName: {{ .secretName }}

{{- end }}
